### ISSUE TITLE
Deploy to NPM

### ISSUE THREAD

**Issue by cecilia-sanare** [jdforsythe/angular-aba-routing-validation#4]
### Description

Currently `angular-aba-routing-validation` isn't being deployed to npm.

### Solution

You can either deploy manually to npm.

**OR**

You could setup an automated deployment using [semantic-release](https://github.com/semantic-release/semantic-release).

**Similar to what the following repos have done:**
- [angular-formly](https://github.com/formly-js/angular-formly)
- [salte-filter](https://github.com/salte-io/salte-filter)

### Workaround

**Install directly from github via:**
```sh
$ npm i jdforsythe/angular-aba-routing-validation
```

**NOTE: npm will log warnings about `angular` being an unmet peer dependency**

**Comment by jdforsythe** [comment]
I'll try to get around to this, but a PR would be welcome.
